import type { Metadata } from "next";
import "./globals.css";
import { siteConfig } from "@/config/site";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        style={
          {
            "--color-primary": siteConfig.colors.primary,
            "--color-primary-hover": siteConfig.colors.primaryHover,
            "--color-secondary": siteConfig.colors.secondary,
            "--color-accent": siteConfig.colors.accent,
            "--color-background": siteConfig.colors.background,
            "--color-text": siteConfig.colors.text,
          } as React.CSSProperties
        }
      >
        {children}
      </body>
    </html>
  );
}
